/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/entrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abre uma sessão */
        post: operations["IdentidadeController_entrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encerra a sessão atual */
        post: operations["IdentidadeController_sair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/eu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quem está logado */
        get: operations["IdentidadeController_eu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/senha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Troca a própria senha e derruba as outras sessões */
        post: operations["IdentidadeController_trocarSenha"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os usuários */
        get: operations["IdentidadeController_listarUsuarios"];
        put?: never;
        /** Cria um usuário */
        post: operations["IdentidadeController_criarUsuario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/usuarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Altera um usuário */
        patch: operations["IdentidadeController_alterarUsuario"];
        trace?: never;
    };
    "/api/v1/auth/senha/esqueci": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pede o link de redefinição de senha */
        post: operations["IdentidadeController_pedirRedefinicao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/senha/redefinir/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Confere se o link de redefinição ainda vale */
        get: operations["IdentidadeController_conferirToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/senha/redefinir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redefine a senha usando o link do e-mail */
        post: operations["IdentidadeController_redefinirSenha"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bulario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca formulações por doença, ativo ou nome */
        get: operations["BularioController_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bulario/linhas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** As linhas terapêuticas, com quantas formulações cada uma tem */
        get: operations["BularioController_linhas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bulario/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Uma formulação inteira, como o guia a escreve */
        get: operations["BularioController_achar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/insumos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca insumos pelo nome ou pelo código */
        get: operations["CatalogoController_insumos"];
        put?: never;
        /** Cadastra um insumo */
        post: operations["CatalogoController_criarInsumo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/formas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Formas farmacêuticas disponíveis */
        get: operations["CatalogoController_formas"];
        put?: never;
        /** Cadastra uma forma farmacêutica */
        post: operations["CatalogoController_criarForma"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/orcamento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calcula o preço de uma formulação */
        post: operations["CatalogoController_orcamento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/orcamento/detalhado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calcula o preço e mostra a composição */
        post: operations["CatalogoController_orcamentoDetalhado"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/insumos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Um insumo, com custo e markup */
        get: operations["CatalogoController_insumo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Altera um insumo */
        patch: operations["CatalogoController_alterarInsumo"];
        trace?: never;
    };
    "/api/v1/catalogo/restricoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Todas as proibições de insumo por forma */
        get: operations["CatalogoController_restricoes"];
        put?: never;
        /** Proíbe um insumo numa forma */
        post: operations["CatalogoController_criarRestricao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/formas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Altera uma forma farmacêutica */
        patch: operations["CatalogoController_alterarForma"];
        trace?: never;
    };
    "/api/v1/catalogo/restricoes/{insumoId}/{formaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a proibição de um insumo numa forma */
        delete: operations["CatalogoController_removerRestricao"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/faixas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cadastra uma faixa terapêutica */
        post: operations["CatalogoController_criarFaixa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/condicoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Condições comerciais em vigor */
        get: operations["CatalogoController_lerCondicoes"];
        /** Altera as condições comerciais */
        put: operations["CatalogoController_gravarCondicoes"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogo/insumos/{id}/faixas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Faixas terapêuticas de um insumo */
        get: operations["CatalogoController_faixasDoInsumo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clinicas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clínicas visíveis para quem perguntou */
        get: operations["ClinicasController_listar"];
        put?: never;
        /** Cadastra uma clínica parceira */
        post: operations["ClinicasController_criar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clinicas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cadastro da clínica */
        get: operations["ClinicasController_achar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Altera o cadastro, inclusive a situação */
        patch: operations["ClinicasController_alterar"];
        trace?: never;
    };
    "/api/v1/clinicas/{id}/logotipo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Baixa o logotipo da clínica */
        get: operations["ClinicasController_baixarLogotipo"];
        /** Grava o logotipo impresso no cabeçalho da receita */
        put: operations["ClinicasController_enviarLogotipo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clinicas/{id}/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quem atende ou opera nesta clínica */
        get: operations["ClinicasController_listarVinculos"];
        put?: never;
        /** Vincula alguém à clínica */
        post: operations["ClinicasController_vincular"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clinicas/{id}/usuarios/{usuarioId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Encerra o vínculo */
        delete: operations["ClinicasController_desvincular"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receituario/tutores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca tutores pelo nome ou pelo CPF */
        get: operations["CadastroController_listarTutores"];
        put?: never;
        /** Cadastra um tutor */
        post: operations["CadastroController_criarTutor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receituario/tutores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ficha do tutor */
        get: operations["CadastroController_acharTutor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Corrige a ficha do tutor */
        patch: operations["CadastroController_alterarTutor"];
        trace?: never;
    };
    "/api/v1/receituario/pacientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca pacientes */
        get: operations["CadastroController_listarPacientes"];
        put?: never;
        /** Cadastra um paciente */
        post: operations["CadastroController_criarPaciente"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receituario/pacientes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ficha do paciente */
        get: operations["CadastroController_acharPaciente"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Corrige a ficha do paciente */
        patch: operations["CadastroController_alterarPaciente"];
        trace?: never;
    };
    "/api/v1/receituario/receitas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista receitas */
        get: operations["ReceitaController_listar"];
        put?: never;
        /** Abre um rascunho de receita */
        post: operations["ReceitaController_criar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receituario/receitas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A receita inteira, com fórmulas, preço e avisos */
        get: operations["ReceitaController_achar"];
        /** Regrava o rascunho */
        put: operations["ReceitaController_salvar"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receituario/receitas/{id}/emitir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Emite a receita: numera, congela e passa a valer */
        post: operations["ReceitaController_emitir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receituario/receitas/{id}/cancelar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancela a receita, com motivo */
        post: operations["ReceitaController_cancelar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receituario/receitas/{id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A receita emitida em PDF, para imprimir ou anexar */
        get: operations["DocumentoController_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/publico/receitas/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A receita que o tutor abre pelo link */
        get: operations["PublicoController_consultar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/publico/receitas/{token}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** O PDF da receita, pelo mesmo link */
        get: operations["PublicoController_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/painel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Métricas da tela inicial, conforme o papel */
        get: operations["PainelController_montar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pedidos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A fila da farmácia */
        get: operations["PedidosController_listar"];
        put?: never;
        /** Manda uma receita emitida para a farmácia */
        post: operations["PedidosController_enviar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pedidos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Um pedido */
        get: operations["PedidosController_achar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pedidos/{id}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move o pedido para o próximo estado */
        post: operations["PedidosController_mudarEstado"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness da API */
        get: operations["HealthController_verificar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EntrarDto: {
            email: string;
            senha: string;
        };
        EuDto: {
            /** Format: uuid */
            id: string;
            nome: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            papel: "ADMIN" | "VETERINARIO" | "FARMACIA" | "CLINICA";
            crmv: string | null;
        };
        TrocarSenhaDto: {
            senhaAtual: string;
            senhaNova: string;
        };
        ListaDeUsuariosDto: {
            usuarios: {
                /** Format: uuid */
                id: string;
                nome: string;
                /** Format: email */
                email: string;
                /** @enum {string} */
                papel: "ADMIN" | "VETERINARIO" | "FARMACIA" | "CLINICA";
                crmv: string | null;
                bloqueado: boolean;
                desativado: boolean;
                /** Format: date-time */
                criadoEm: string;
            }[];
        };
        CriarUsuarioDto: {
            email: string;
            nome: string;
            /** @enum {string} */
            papel: "ADMIN" | "VETERINARIO" | "FARMACIA" | "CLINICA";
            senha: string;
            crmv?: string | null;
        };
        AlterarUsuarioDto: {
            nome?: string;
            /** @enum {string} */
            papel?: "ADMIN" | "VETERINARIO" | "FARMACIA" | "CLINICA";
            crmv?: string | null;
            desativado?: boolean;
        };
        PedirRedefinicaoDto: {
            email: string;
        };
        RedefinirSenhaDto: {
            token: string;
            senhaNova: string;
        };
        ListaDoBularioDto: {
            formulacoes: {
                /** Format: uuid */
                id: string;
                numero: string;
                titulo: string;
                linhaTerapeutica: string;
                linhaExclusiva: string | null;
                formaFarmaceutica: string | null;
                indicacao: string | null;
                especies: ("CANINO" | "FELINO" | "EQUINO" | "AVE" | "ROEDOR" | "REPTIL")[];
            }[];
            total: number;
        };
        LinhasDoBularioDto: {
            linhas: {
                nome: string;
                quantidade: number;
            }[];
        };
        FormulacaoDoBularioDto: {
            /** Format: uuid */
            id: string;
            numero: string;
            titulo: string;
            linhaTerapeutica: string;
            linhaExclusiva: string | null;
            formaFarmaceutica: string | null;
            indicacao: string | null;
            especies: ("CANINO" | "FELINO" | "EQUINO" | "AVE" | "ROEDOR" | "REPTIL")[];
            diferencial: string | null;
            composicao: string | null;
            modoDeUsar: string | null;
            observacoes: string | null;
        };
        ListaDeInsumosDto: {
            insumos: {
                /** Format: uuid */
                id: string;
                codigo: string;
                descricao: string;
                controlado: boolean;
                listaDeControle: string | null;
                /** @enum {string} */
                estoque: "disponivel" | "em-falta" | "desconhecido";
                formasProibidas: {
                    /** Format: uuid */
                    formaId: string;
                    nome: string;
                    motivo: string;
                }[];
            }[];
        };
        ListaDeFormasDto: {
            formas: {
                /** Format: uuid */
                id: string;
                nome: string;
                aceitaAroma: boolean;
            }[];
        };
        PrecificarDto: {
            /** Format: uuid */
            formaId: string;
            clinicaId?: string | null;
            itens: {
                /** Format: uuid */
                insumoId: string;
                doseMg: number;
                quantidade: number;
            }[];
            paciente?: {
                /** @enum {string} */
                especie: "CANINO" | "FELINO" | "EQUINO" | "AVE" | "ROEDOR" | "REPTIL";
                pesoEmGramas: number;
            };
        };
        OrcamentoDto: {
            valorFinalEmCentavos: number;
            forma: string;
            avisos: {
                /** @enum {string} */
                tipo: "sem-estoque" | "controlado" | "antimicrobiano" | "fora-da-faixa" | "sem-referencia";
                insumoId: string | null;
                texto: string;
            }[];
            impedimentos: {
                insumoId: string | null;
                texto: string;
            }[];
        };
        OrcamentoDetalhadoDto: {
            valorFinalEmCentavos: number;
            forma: string;
            avisos: {
                /** @enum {string} */
                tipo: "sem-estoque" | "controlado" | "antimicrobiano" | "fora-da-faixa" | "sem-referencia";
                insumoId: string | null;
                texto: string;
            }[];
            impedimentos: {
                insumoId: string | null;
                texto: string;
            }[];
            itens: {
                /** Format: uuid */
                insumoId: string;
                descricao: string;
                massaTotalEmMiligramas: number;
                custoEmCentavos: number;
            }[];
            totalDeMateriaPrimaEmCentavos: number;
            taxaDeManipulacaoEmCentavos: number;
            custoDeEmbalagensEmCentavos: number;
            subtotalEmCentavos: number;
            descontoEmCentavos: number;
            adicionalDeEntregaEmCentavos: number;
            adicionalDeBiscoitoEmCentavos: number;
        };
        CriarInsumoDto: {
            codigo: string;
            descricao: string;
            custoPorGramaEmMicro: number;
            /** @default 0 */
            custoDeReferenciaPorGramaEmMicro: number;
            markupEmCentesimos: number;
            estoqueEmMiligramas?: number | null;
            /** @default false */
            controlado: boolean;
            listaDeControle?: string | null;
        };
        InsumoAdminDto: {
            /** Format: uuid */
            id: string;
            codigo: string;
            descricao: string;
            controlado: boolean;
            listaDeControle: string | null;
            /** @enum {string} */
            estoque: "disponivel" | "em-falta" | "desconhecido";
            formasProibidas: {
                /** Format: uuid */
                formaId: string;
                nome: string;
                motivo: string;
            }[];
            custoPorGramaEmMicro: number;
            custoDeReferenciaPorGramaEmMicro: number;
            markupEmCentesimos: number;
            estoqueEmMiligramas: number | null;
        };
        ListaDeRestricoesDto: {
            restricoes: {
                /** Format: uuid */
                insumoId: string;
                insumoCodigo: string;
                insumoDescricao: string;
                /** Format: uuid */
                formaId: string;
                formaNome: string;
                motivo: string;
            }[];
        };
        AlterarInsumoDto: {
            descricao?: string;
            custoPorGramaEmMicro?: number;
            custoDeReferenciaPorGramaEmMicro?: number;
            markupEmCentesimos?: number;
            estoqueEmMiligramas?: number | null;
            controlado?: boolean;
            listaDeControle?: string | null;
        };
        CriarFormaDto: {
            nome: string;
            aceitaAroma?: boolean;
        };
        FormaDto: {
            /** Format: uuid */
            id: string;
            nome: string;
            aceitaAroma: boolean;
        };
        AlterarFormaDto: {
            aceitaAroma?: boolean;
            desativada?: boolean;
        };
        CriarRestricaoDto: {
            /** Format: uuid */
            insumoId: string;
            /** Format: uuid */
            formaId: string;
            motivo: string;
        };
        CriarFaixaDto: {
            /** Format: uuid */
            insumoId: string;
            /** @enum {string} */
            especie: "CANINO" | "FELINO" | "EQUINO" | "AVE" | "ROEDOR" | "REPTIL";
            pesoMinimoEmGramas?: number | null;
            pesoMaximoEmGramas?: number | null;
            doseMinimaEmMicrogramasPorKg: number;
            doseMaximaEmMicrogramasPorKg: number;
            duracaoMaximaEmDias?: number | null;
            observacao?: string | null;
        };
        FaixaDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            insumoId: string;
            /** @enum {string} */
            especie: "CANINO" | "FELINO" | "EQUINO" | "AVE" | "ROEDOR" | "REPTIL";
            pesoMinimoEmGramas: number | null;
            pesoMaximoEmGramas: number | null;
            doseMinimaEmMicrogramasPorKg: number;
            doseMaximaEmMicrogramasPorKg: number;
            duracaoMaximaEmDias: number | null;
            observacao: string | null;
        };
        CondicoesDto: {
            taxaDeManipulacaoEmCentavos: number;
            custoDeEmbalagensEmCentavos: number;
            descontoEmPontosBase: number;
            adicionalDeEntregaEmCentavos: number;
            adicionalDeBiscoitoEmCentavos: number;
        };
        ListaDeClinicasDto: {
            clinicas: {
                /** Format: uuid */
                id: string;
                razaoSocial: string;
                nomeFantasia: string;
                cnpj: string;
                inscricaoEstadual: string | null;
                email: string;
                telefone: string | null;
                whatsapp: string | null;
                cep: string | null;
                logradouro: string | null;
                numero: string | null;
                complemento: string | null;
                bairro: string | null;
                cidade: string | null;
                uf: string | null;
                responsavelLegal: string;
                cpfDoResponsavel: string | null;
                /** @enum {string} */
                situacao: "PENDENTE" | "ATIVA" | "SUSPENSA";
                observacoesInternas: string | null;
                temLogotipo: boolean;
                /** Format: date-time */
                atualizadaEm: string;
                quantidadeDeUsuarios: number;
            }[];
        };
        ClinicaDto: {
            /** Format: uuid */
            id: string;
            razaoSocial: string;
            nomeFantasia: string;
            cnpj: string;
            inscricaoEstadual: string | null;
            email: string;
            telefone: string | null;
            whatsapp: string | null;
            cep: string | null;
            logradouro: string | null;
            numero: string | null;
            complemento: string | null;
            bairro: string | null;
            cidade: string | null;
            uf: string | null;
            responsavelLegal: string;
            cpfDoResponsavel: string | null;
            /** @enum {string} */
            situacao: "PENDENTE" | "ATIVA" | "SUSPENSA";
            observacoesInternas: string | null;
            temLogotipo: boolean;
            /** Format: date-time */
            atualizadaEm: string;
            quantidadeDeUsuarios: number;
        };
        CriarClinicaDto: {
            razaoSocial: string;
            nomeFantasia: string;
            cnpj: string;
            inscricaoEstadual?: string | null;
            /** Format: email */
            email: string;
            telefone?: string | null;
            whatsapp?: string | null;
            cep?: string | null;
            logradouro?: string | null;
            numero?: string | null;
            complemento?: string | null;
            bairro?: string | null;
            cidade?: string | null;
            uf?: string | null;
            responsavelLegal: string;
            cpfDoResponsavel?: string | null;
            observacoesInternas?: string | null;
        };
        AlterarClinicaDto: {
            razaoSocial?: string;
            nomeFantasia?: string;
            cnpj?: string;
            inscricaoEstadual?: string | null;
            /** Format: email */
            email?: string;
            telefone?: string | null;
            whatsapp?: string | null;
            cep?: string | null;
            logradouro?: string | null;
            numero?: string | null;
            complemento?: string | null;
            bairro?: string | null;
            cidade?: string | null;
            uf?: string | null;
            responsavelLegal?: string;
            cpfDoResponsavel?: string | null;
            observacoesInternas?: string | null;
            /** @enum {string} */
            situacao?: "PENDENTE" | "ATIVA" | "SUSPENSA";
        };
        EnviarLogotipoDto: {
            /** @enum {string} */
            tipo: "image/png" | "image/jpeg" | "image/webp" | "image/svg+xml";
            conteudoBase64: string;
        };
        ListaDeVinculosDto: {
            vinculos: {
                /** Format: uuid */
                usuarioId: string;
                nome: string;
                email: string;
                /** @enum {string} */
                papel: "ADMIN" | "VETERINARIO" | "FARMACIA" | "CLINICA";
                crmv: string | null;
                cargo: string | null;
            }[];
        };
        VincularDto: {
            /** Format: uuid */
            usuarioId: string;
            cargo?: string | null;
        };
        CriarTutorDto: {
            nome: string;
            cpf?: string | null;
            email?: string | null;
            telefone?: string | null;
            cep?: string | null;
            logradouro?: string | null;
            numero?: string | null;
            complemento?: string | null;
            bairro?: string | null;
            cidade?: string | null;
            uf?: string | null;
            observacoes?: string | null;
        };
        TutorDto: {
            /** Format: uuid */
            id: string;
            nome: string;
            cpf: string | null;
            email: string | null;
            telefone: string | null;
            cep: string | null;
            logradouro: string | null;
            numero: string | null;
            complemento: string | null;
            bairro: string | null;
            cidade: string | null;
            uf: string | null;
            observacoes: string | null;
            quantidadeDePacientes: number;
        };
        ListaDeTutoresDto: {
            tutores: {
                /** Format: uuid */
                id: string;
                nome: string;
                cpf: string | null;
                email: string | null;
                telefone: string | null;
                cep: string | null;
                logradouro: string | null;
                numero: string | null;
                complemento: string | null;
                bairro: string | null;
                cidade: string | null;
                uf: string | null;
                observacoes: string | null;
                quantidadeDePacientes: number;
            }[];
        };
        AlterarTutorDto: {
            nome?: string;
            cpf?: string | null;
            email?: string | null;
            telefone?: string | null;
            cep?: string | null;
            logradouro?: string | null;
            numero?: string | null;
            complemento?: string | null;
            bairro?: string | null;
            cidade?: string | null;
            uf?: string | null;
            observacoes?: string | null;
        };
        CriarPacienteDto: {
            /** Format: uuid */
            tutorId: string;
            nome: string;
            /** @enum {string} */
            especie: "CANINO" | "FELINO" | "EQUINO" | "AVE" | "ROEDOR" | "REPTIL";
            raca?: string | null;
            sexo?: ("MACHO" | "FEMEA") | null;
            castrado?: boolean;
            pesoEmGramas?: number | null;
            nascimentoEm?: string | null;
            observacoes?: string | null;
        };
        PacienteDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tutorId: string;
            tutorNome: string;
            nome: string;
            /** @enum {string} */
            especie: "CANINO" | "FELINO" | "EQUINO" | "AVE" | "ROEDOR" | "REPTIL";
            raca: string | null;
            sexo: ("MACHO" | "FEMEA") | null;
            castrado: boolean;
            pesoEmGramas: number | null;
            pesoAferidoEm: string | null;
            nascimentoEm: string | null;
            observacoes: string | null;
            obito: boolean;
        };
        ListaDePacientesDto: {
            pacientes: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                tutorId: string;
                tutorNome: string;
                nome: string;
                /** @enum {string} */
                especie: "CANINO" | "FELINO" | "EQUINO" | "AVE" | "ROEDOR" | "REPTIL";
                raca: string | null;
                sexo: ("MACHO" | "FEMEA") | null;
                castrado: boolean;
                pesoEmGramas: number | null;
                pesoAferidoEm: string | null;
                nascimentoEm: string | null;
                observacoes: string | null;
                obito: boolean;
            }[];
        };
        AlterarPacienteDto: {
            nome?: string;
            /** @enum {string} */
            especie?: "CANINO" | "FELINO" | "EQUINO" | "AVE" | "ROEDOR" | "REPTIL";
            raca?: string | null;
            sexo?: ("MACHO" | "FEMEA") | null;
            castrado?: boolean;
            pesoEmGramas?: number | null;
            nascimentoEm?: string | null;
            observacoes?: string | null;
        };
        SalvarReceitaDto: {
            /** Format: uuid */
            pacienteId: string;
            clinicaId?: string | null;
            observacoes?: string | null;
            formulacoes: {
                /** Format: uuid */
                formaId: string;
                frequenciaHoras: 24 | 12 | 8 | 6;
                dias: number;
                quantidade?: number;
                orientacao?: string | null;
                aroma?: ("CARNE" | "FRANGO" | "BANANA" | "MORANGO") | null;
                usoContinuo?: boolean;
                itens: {
                    /** Format: uuid */
                    insumoId: string;
                    doseMg: number;
                }[];
            }[];
        };
        ReceitaDto: {
            /** Format: uuid */
            id: string;
            numero: number | null;
            /** @enum {string} */
            estado: "RASCUNHO" | "EMITIDA" | "CANCELADA";
            /** @enum {string} */
            situacao: "rascunho" | "valida" | "vencida" | "cancelada";
            /** Format: uuid */
            veterinarioId: string;
            veterinarioNome: string;
            crmv: string | null;
            /** Format: uuid */
            pacienteId: string;
            pacienteNome: string;
            tutorNome: string;
            clinicaId: string | null;
            clinicaNome: string | null;
            clinicaCnpj: string | null;
            pesoDoPacienteEmGramas: number | null;
            emitidaEm: string | null;
            validaAte: string | null;
            prazoEmDias: number | null;
            prazoMotivo: string | null;
            canceladaEm: string | null;
            motivoDoCancelamento: string | null;
            observacoes: string | null;
            tokenPublico: string | null;
            formulacoes: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                formaId: string;
                forma: string;
                frequenciaHoras: number;
                dias: number;
                quantidade: number;
                orientacao: string | null;
                aroma: ("CARNE" | "FRANGO" | "BANANA" | "MORANGO") | null;
                usoContinuo: boolean;
                valorEmCentavos: number | null;
                itens: {
                    /** Format: uuid */
                    insumoId: string;
                    codigo: string;
                    descricao: string;
                    doseMg: number;
                    listaDeControle: string | null;
                }[];
                avisos: {
                    /** @enum {string} */
                    tipo: "sem-estoque" | "controlado" | "antimicrobiano" | "fora-da-faixa" | "sem-referencia" | "duracao-acima";
                    insumoId: string | null;
                    texto: string;
                }[];
                impedimentos: {
                    insumoId: string | null;
                    texto: string;
                }[];
            }[];
            valorTotalEmCentavos: number;
            /** Format: date-time */
            criadaEm: string;
        };
        ListaDeReceitasDto: {
            receitas: {
                /** Format: uuid */
                id: string;
                numero: number | null;
                /** @enum {string} */
                estado: "RASCUNHO" | "EMITIDA" | "CANCELADA";
                /** @enum {string} */
                situacao: "rascunho" | "valida" | "vencida" | "cancelada";
                pacienteNome: string;
                tutorNome: string;
                veterinarioNome: string;
                emitidaEm: string | null;
                validaAte: string | null;
                /** Format: date-time */
                criadaEm: string;
            }[];
        };
        CancelarReceitaDto: {
            motivo: string;
        };
        ReceitaPublicaDto: {
            numero: number;
            /** @enum {string} */
            situacao: "rascunho" | "valida" | "vencida" | "cancelada";
            /** Format: date-time */
            emitidaEm: string;
            /** Format: date-time */
            validaAte: string;
            prazoMotivo: string;
            motivoDoCancelamento: string | null;
            clinicaNome: string | null;
            veterinarioNome: string;
            crmv: string;
            tutorNome: string;
            tutorCpf: string | null;
            pacienteNome: string;
            pacienteEspecie: string;
            formulacoes: {
                forma: string;
                quantidade: number;
                frequenciaHoras: number;
                dias: number;
                orientacao: string | null;
                aroma: ("CARNE" | "FRANGO" | "BANANA" | "MORANGO") | null;
                usoContinuo: boolean;
                valorEmCentavos: number | null;
                itens: {
                    descricao: string;
                    doseMg: number;
                }[];
            }[];
            valorTotalEmCentavos: number;
            pedido: {
                numero: number;
                /** @enum {string} */
                estado: "EM_ANALISE" | "EM_PRODUCAO" | "PRONTO" | "ENTREGUE" | "CANCELADO";
                situacao: string;
            } | null;
        };
        PainelDto: {
            rascunhos: number;
            emitidasNoMes: number;
            vencendo: number;
            valorPrescritoNoMesEmCentavos: number;
            fila: {
                /** @enum {string} */
                estado: "EM_ANALISE" | "EM_PRODUCAO" | "PRONTO";
                quantidade: number;
            }[] | null;
            topVeterinarios: {
                /** Format: uuid */
                id: string;
                nome: string;
                crmv: string | null;
                receitas: number;
            }[] | null;
            ultimas: {
                /** Format: uuid */
                id: string;
                numero: number | null;
                pacienteNome: string;
                tutorNome: string;
                /** @enum {string} */
                estado: "RASCUNHO" | "EMITIDA" | "CANCELADA";
                /** Format: date-time */
                criadaEm: string;
            }[];
        };
        EnviarPedidoDto: {
            /** Format: uuid */
            receitaId: string;
            /** @enum {string} */
            destino: "CLINICA" | "TUTOR";
            observacoes?: string;
        };
        PedidoDto: {
            /** Format: uuid */
            id: string;
            numero: number;
            /** @enum {string} */
            estado: "EM_ANALISE" | "EM_PRODUCAO" | "PRONTO" | "ENTREGUE" | "CANCELADO";
            /** @enum {string} */
            destino: "CLINICA" | "TUTOR";
            enderecoDeEntrega: string;
            observacoes: string | null;
            motivoDoCancelamento: string | null;
            /** Format: uuid */
            receitaId: string;
            receitaNumero: number | null;
            pacienteNome: string;
            tutorNome: string;
            clinicaNome: string | null;
            veterinarioNome: string;
            enviadoPorNome: string;
            formulacoes: {
                forma: string;
                quantidade: number;
                aroma: string | null;
                usoContinuo: boolean;
                itens: {
                    descricao: string;
                    doseMg: number;
                }[];
            }[];
            valorTotalEmCentavos: number;
            /** Format: date-time */
            criadoEm: string;
            producaoEm: string | null;
            prontoEm: string | null;
            entregueEm: string | null;
        };
        ListaDePedidosDto: {
            pedidos: {
                /** Format: uuid */
                id: string;
                numero: number;
                /** @enum {string} */
                estado: "EM_ANALISE" | "EM_PRODUCAO" | "PRONTO" | "ENTREGUE" | "CANCELADO";
                /** @enum {string} */
                destino: "CLINICA" | "TUTOR";
                enderecoDeEntrega: string;
                observacoes: string | null;
                motivoDoCancelamento: string | null;
                /** Format: uuid */
                receitaId: string;
                receitaNumero: number | null;
                pacienteNome: string;
                tutorNome: string;
                clinicaNome: string | null;
                veterinarioNome: string;
                enviadoPorNome: string;
                formulacoes: {
                    forma: string;
                    quantidade: number;
                    aroma: string | null;
                    usoContinuo: boolean;
                    itens: {
                        descricao: string;
                        doseMg: number;
                    }[];
                }[];
                valorTotalEmCentavos: number;
                /** Format: date-time */
                criadoEm: string;
                producaoEm: string | null;
                prontoEm: string | null;
                entregueEm: string | null;
            }[];
        };
        MudarEstadoDto: {
            /** @enum {string} */
            estado: "EM_ANALISE" | "EM_PRODUCAO" | "PRONTO" | "ENTREGUE" | "CANCELADO";
            motivo?: string;
        };
        /** @description Sinal de vida da API */
        SaudeDto: {
            /** @constant */
            status: "ok";
            /**
             * Format: date-time
             * @description Momento da verificação, em ISO 8601 UTC
             */
            timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    IdentidadeController_entrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntrarDto"];
            };
        };
        responses: {
            /** @description Sessão aberta; os cookies vão na resposta. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description E-mail ou senha incorretos. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IdentidadeController_sair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessão encerrada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IdentidadeController_eu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EuDto"];
                };
            };
        };
    };
    IdentidadeController_trocarSenha: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrocarSenhaDto"];
            };
        };
        responses: {
            /** @description Senha trocada; é preciso entrar de novo. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Senha atual incorreta. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IdentidadeController_listarUsuarios: {
        parameters: {
            query?: {
                papel?: "ADMIN" | "VETERINARIO" | "FARMACIA" | "CLINICA";
                busca?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaDeUsuariosDto"];
                };
            };
            /** @description Só administrador lista usuários. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IdentidadeController_criarUsuario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarUsuarioDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EuDto"];
                };
            };
            /** @description Só administrador cria usuário. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IdentidadeController_alterarUsuario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlterarUsuarioDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EuDto"];
                };
            };
            /** @description Só administrador altera usuário. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IdentidadeController_pedirRedefinicao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PedirRedefinicaoDto"];
            };
        };
        responses: {
            /** @description Pedido recebido. A resposta não diz se a conta existe. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IdentidadeController_conferirToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O link vale. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IdentidadeController_redefinirSenha: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedefinirSenhaDto"];
            };
        };
        responses: {
            /** @description Senha trocada; é preciso entrar de novo. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BularioController_listar: {
        parameters: {
            query?: {
                busca?: string;
                linhaTerapeutica?: string;
                especie?: "CANINO" | "FELINO" | "EQUINO" | "AVE" | "ROEDOR" | "REPTIL";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaDoBularioDto"];
                };
            };
        };
    };
    BularioController_linhas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinhasDoBularioDto"];
                };
            };
        };
    };
    BularioController_achar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormulacaoDoBularioDto"];
                };
            };
        };
    };
    CatalogoController_insumos: {
        parameters: {
            query?: {
                busca?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaDeInsumosDto"];
                };
            };
        };
    };
    CatalogoController_criarInsumo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarInsumoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsumoAdminDto"];
                };
            };
        };
    };
    CatalogoController_formas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaDeFormasDto"];
                };
            };
        };
    };
    CatalogoController_criarForma: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarFormaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormaDto"];
                };
            };
        };
    };
    CatalogoController_orcamento: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrecificarDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrcamentoDto"];
                };
            };
        };
    };
    CatalogoController_orcamentoDetalhado: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrecificarDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrcamentoDetalhadoDto"];
                };
            };
            /** @description A composição do preço não é visível para o prescritor. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogoController_insumo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsumoAdminDto"];
                };
            };
        };
    };
    CatalogoController_alterarInsumo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlterarInsumoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsumoAdminDto"];
                };
            };
        };
    };
    CatalogoController_restricoes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaDeRestricoesDto"];
                };
            };
        };
    };
    CatalogoController_criarRestricao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarRestricaoDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogoController_alterarForma: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlterarFormaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormaDto"];
                };
            };
        };
    };
    CatalogoController_removerRestricao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                insumoId: string;
                formaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogoController_criarFaixa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarFaixaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaixaDto"];
                };
            };
        };
    };
    CatalogoController_lerCondicoes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CondicoesDto"];
                };
            };
        };
    };
    CatalogoController_gravarCondicoes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CondicoesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CondicoesDto"];
                };
            };
        };
    };
    CatalogoController_faixasDoInsumo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaixaDto"][];
                };
            };
        };
    };
    ClinicasController_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaDeClinicasDto"];
                };
            };
        };
    };
    ClinicasController_criar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarClinicaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicaDto"];
                };
            };
        };
    };
    ClinicasController_achar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicaDto"];
                };
            };
            /** @description Não existe, ou não é visível para quem perguntou. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicasController_alterar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlterarClinicaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicaDto"];
                };
            };
        };
    };
    ClinicasController_baixarLogotipo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O arquivo do logotipo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A clínica não tem logotipo. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicasController_enviarLogotipo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnviarLogotipoDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicasController_listarVinculos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaDeVinculosDto"];
                };
            };
        };
    };
    ClinicasController_vincular: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VincularDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicasController_desvincular: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                usuarioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CadastroController_listarTutores: {
        parameters: {
            query?: {
                busca?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaDeTutoresDto"];
                };
            };
        };
    };
    CadastroController_criarTutor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarTutorDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TutorDto"];
                };
            };
        };
    };
    CadastroController_acharTutor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TutorDto"];
                };
            };
            /** @description Não existe, ou não é visível para quem perguntou. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CadastroController_alterarTutor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlterarTutorDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TutorDto"];
                };
            };
        };
    };
    CadastroController_listarPacientes: {
        parameters: {
            query?: {
                tutorId?: string;
                busca?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaDePacientesDto"];
                };
            };
        };
    };
    CadastroController_criarPaciente: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarPacienteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PacienteDto"];
                };
            };
        };
    };
    CadastroController_acharPaciente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PacienteDto"];
                };
            };
        };
    };
    CadastroController_alterarPaciente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlterarPacienteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PacienteDto"];
                };
            };
        };
    };
    ReceitaController_listar: {
        parameters: {
            query?: {
                pacienteId?: string;
                estado?: "RASCUNHO" | "EMITIDA" | "CANCELADA";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaDeReceitasDto"];
                };
            };
        };
    };
    ReceitaController_criar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalvarReceitaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceitaDto"];
                };
            };
        };
    };
    ReceitaController_achar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceitaDto"];
                };
            };
            /** @description Não existe, ou não é visível para quem perguntou. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReceitaController_salvar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalvarReceitaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceitaDto"];
                };
            };
            /** @description Receita emitida não se altera. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReceitaController_emitir: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceitaDto"];
                };
            };
            /** @description Falta CRMV, falta peso do paciente, há impedimento na fórmula ou lista sem prazo. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReceitaController_cancelar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelarReceitaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceitaDto"];
                };
            };
        };
    };
    DocumentoController_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublicoController_consultar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceitaPublicaDto"];
                };
            };
            /** @description Link inválido, ou receita ainda não emitida. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublicoController_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Link inválido, ou receita ainda não emitida. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PainelController_montar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PainelDto"];
                };
            };
        };
    };
    PedidosController_listar: {
        parameters: {
            query?: {
                estado?: string;
                emAberto?: "true" | "false";
                receitaId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaDePedidosDto"];
                };
            };
        };
    };
    PedidosController_enviar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnviarPedidoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PedidoDto"];
                };
            };
            /** @description Receita não válida, ou destino sem endereço. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Esta receita já tem um pedido em andamento. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PedidosController_achar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PedidoDto"];
                };
            };
            /** @description Não existe, ou não é visível para quem perguntou. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PedidosController_mudarEstado: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MudarEstadoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PedidoDto"];
                };
            };
            /** @description Transição não permitida, ou falta o motivo. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_verificar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaudeDto"];
                };
            };
        };
    };
}
